watch_stylesheet: true
watch_config: true
debug: false
update_check: true
komorebi:
  start_command: "komorebic start"
  stop_command: "komorebic stop"
  reload_command: "komorebic stop && komorebic start"
glazewm:
  start_command: "glazewm.exe start"
  stop_command: "glazewm.exe command wm-exit"
  reload_command: "glazewm.exe command wm-exit && glazewm.exe start"
bars:
  status-bar:
    enabled: true
    screens: ['*']
    class_name: "yasb-bar"
    alignment:
      position: "top"
      center: false
    animation:
      enabled: true
      duration: 800
    blur_effect:
      enabled: true
      acrylic: true
      dark_mode: true
      round_corners: true
      border_color: none
    window_flags:
      always_on_top: false
      windows_app_bar: true
    dimensions:
      width: "100%"
      height: 35
    padding:
      top: 12
      left: 11
      bottom: 4
      right: 11
    widgets:
      left:
        [
          "home",
          "bin",
          "update_check",
          "wm_controls"
        ]
      center:
        [
          "notifications",
          "apps",          
          "clock",
          "weather",
          "wallpapers"
        ]
      right:
        [
          "taskbar",
          "media",
          "system_monitor",
          "bluetooth",
          "power_menu"
        ]

widgets:
  # Grouper Widgets
  wm_controls:
    type: "yasb.grouper.GrouperWidget"
    options:
      class_name: "wm-controls"
      hide_empty: false
      widgets: ["glazewm_workspaces", "komorebi_control", "komorebi_workspaces", "komorebi_stack"]
      container_shadow:
        enabled: true
        color: "black"
        radius: 3
        offset: [1, 1]

  notifications:
    type: "yasb.grouper.GrouperWidget"
    options:
      class_name: "notifications-group"
      hide_empty: true
      widgets: ["obs", "github", "notes"]
      container_shadow:
        enabled: true
        color: "black"
        radius: 3
        offset: [1, 1]

  system_monitor:
    type: "yasb.grouper.GrouperWidget"
    options:
      class_name: "system-monitor"
      hide_empty: false
      widgets: ["cpu", "memory", "gpu", "disk"]
      container_shadow:
        enabled: true
        color: "black"
        radius: 3
        offset: [1, 1]

  # Individual Widgets
  home:
    type: "yasb.home.HomeWidget"
    options:
      label: "Chrono's PC"
      menu_list:
        - { title: "🏠 Home", path: "~" }
        - { title: "📥 Downloads", path: "C:\\Users\\nucle\\Downloads"}
        - { title: "📄 Documents", path: "C:\\Users\\nucle\\Documents"}
        - { title: "🖼️ Pictures", path: "C:\\Users\\nucle\\Pictures"}
        - { title: "🎬 Videos", path: "C:\\Users\\nucle\\Videos"}
        - { title: "🎮 Games", path: "C:\\Users\\nucle\\Desktop\\Desktop Apps\\Games"}
        - { title: "🎵 Spotify", path: "C:\\Users\\nucle\\AppData\\Roaming\\Microsoft\\Windows\\Start Menu\\Programs\\Spotify.lnk"}
        - { title: "📺 Stremio", path: "C:\\Users\\nucle\\AppData\\Roaming\\Microsoft\\Windows\\Start Menu\\Programs\\Stremio.lnk"}
        - { title: "🎯 Steam", path: "C:\\ProgramData\\Microsoft\\Windows\\Start Menu\\Programs\\Steam\\Steam.lnk"} 
        - { title: "🌐 Zen Browser", path: "C:\\Users\\nucle\\AppData\\Roaming\\Microsoft\\Windows\\Start Menu\\Programs\\Zen.lnk"}
        - { title: "⚙️ iCUE", path: "C:\\ProgramData\\Microsoft\\Windows\\Start Menu\\Corsair\\iCUE.lnk"}   
      system_menu: true
      power_menu: false
      blur: true
      round_corners: true
      round_corners_type: "normal"
      border_color: ""
      distance: 10
  bin:
    type: "yasb.recycle_bin.RecycleBinWidget"
    options:
      label: "<span>{icon}</span>({items_size})"
      icons:
        bin_empty: "\udb82\ude7a"
        bin_filled: "\udb82\ude79"
      callbacks:
        on_left: "open_bin"
        on_right: "toggle_label"
        on_middle: "empty_bin"
      label_shadow:
        enabled: true
        color: "black"
        radius: 3
        offset: [ 1, 1 ]
  update_check:
    type: "yasb.update_check.UpdateCheckWidget"
    options:
      winget_update:
        enabled: false
        label: "<span>\uf0ab</span>{count}"
        interval: 180
        exclude: []
      windows_update:
        enabled: true
        label: "<span>\uf0ab</span>{count}"
        interval: 240
        exclude: []

  komorebi_workspaces:
    type: "komorebi.workspaces.WorkspaceWidget"
    options:
      label_offline: ""
      label_workspace_btn: "{name}"
      label_workspace_active_btn: "{name}"
      label_workspace_populated_btn: "{name}"
      label_default_name: ""
      label_zero_index: false
      hide_empty_workspaces: false
      hide_if_offline: false
      animation: true
      toggle_workspace_layer:
        enabled: false
        tiling_label: "Tiling"
        floating_label: "Floating"
      app_icons: 
        enabled_populated: true
        enabled_active: true
        size: 12
        max_icons: 0
        hide_label: false
        hide_duplicates: false
        hide_floating: false
      btn_shadow:
        enabled: true
        color: "black"
        radius: 3
        offset: [ 1, 1 ]


  komorebi_control:
    type: "komorebi.control.KomorebiControlWidget"
    options:
      label: "<span>\udb80\uddd9</span>"
      icons:
        start: "\uead3"
        stop: "\uead7"
        reload: "\uead2"
      run_ahk: false
      run_whkd: true
      show_version: true
      komorebi_menu:
        blur: true
        round_corners: true
        round_corners_type: 'normal'
        border_color: 'System'
        alignment: 'left'
        direction: 'down'
        offset_top: 6
        offset_left: 0
      label_shadow:
        enabled: true
        color: "black"
        radius: 3
        offset: [ 1, 1 ]

  komorebi_stack:
    type: "komorebi.stack.StackWidget"
    options:
      label_offline: ""
      label_window: "{process}"
      label_window_active: "{title}"
      label_no_window: "No Window"
      label_zero_index: false
      show_icons: "always"
      icon_size: 14
      max_length: 10
      max_length_active: 20
      max_length_ellipsis: ".."
      hide_if_offline: false
      show_only_stack: false
      animation: true
      enable_scroll_switching : true
      container_shadow:
        enabled: true
        color: "#000000"
        offset: [0, 1]
        radius: 2
      btn_shadow:
        enabled: true
        color: "#000000"
        offset: [0, 1]
        radius: 2
      label_shadow:
        enabled: true
        color: "#000000"
        offset: [0, 1]
        radius: 2

  glazewm_restore:
    type: "yasb.custom.CustomWidget"
    options:
      label: "<span>\uf021</span>"
      label_alt: "Fix GlazeWM"
      class_name: "glazewm-restore-widget"
      exec_options:
        run_cmd: "powershell.exe -ExecutionPolicy Bypass -File \"c:\\Users\\nucle\\.glzr\\glazewm\\glazewm-workspace-restore.ps1\""
        run_interval: 0
        return_format: "string"
        hide_empty: true
        use_shell: false
      callbacks:
        on_left: "exec"
        on_middle: "toggle_label"
        on_right: "toggle_label"
      label_shadow:
        enabled: true
        color: "black"
        radius: 3
        offset: [ 1, 1 ]

  glazewm_workspaces:
    type: "glazewm.workspaces.GlazewmWorkspacesWidget"
    options:
      offline_label: "GlazeWM Offline"
      hide_empty_workspaces: true
      hide_if_offline: false

  obs:
    type: "yasb.obs.ObsWidget"
    options:
      connection:
        host: "192.168.2.38"
        port: 4455
        password: "M2zIK7OKeOsIpVes"
      icons:
        recording: "\ueba7"
        stopped: "\ueba5"
        paused: "\ueba7"
      hide_when_not_recording: true
      blinking_icon: true
  github:
    type: "yasb.github.GithubWidget"
    options:
      label: "<span>\ueba1</span>"
      label_alt: "Notifications {data}"
      token: ""
      max_notification: 20
      only_unread: false
      max_field_size: 54
      update_interval: 60
      notification_dot:
        enabled: true
        corner: "bottom_left"
        color: "red"
        margin: [1, 1]
      menu:
        blur: true
        round_corners: true
        round_corners_type: "normal"
        border_color: "System"
        alignment: "right"
        direction: "down"
      label_shadow:
        enabled: true
        color: "black"
        radius: 3
        offset: [1, 1]
      animation:
        enabled: true
        duration: 500
        type: "fadeInOut"

  apps:
    type: "yasb.applications.ApplicationsWidget"
    options:
      label: "{data}"
      app_list:
        - { icon: "\uf489", launch: "warp" }    
        - { icon: "\uf1ff",launch: "C:\\Users\\nucle\\AppData\\Roaming\\Microsoft\\Windows\\Start Menu\\Programs\\Discord Inc\\Discord.lnk" }
        - { icon: "\uef16",launch: "C:\\Users\\nucle\\AppData\\Local\\Programs\\Windsurf\\Windsurf.exe" }
        - { icon: "\udb82\udde8", launch: "C:\\Corsair iCUE5 Software\\iCUE.exe" }
  clock:
    type: "yasb.clock.ClockWidget"
    options:
      label: "<span>\uf017</span> {%I:%M:%S %p}"
      label_alt: "<span>\uf017</span> {%d-%m-%y %I:%M:%S %p}"
      locale: ""
      update_interval: 1000
      timezones: []
      calendar: 
        blur: True
        round_corners: True
        round_corners_type: "normal"
        border_color: "System"
        alignment: "center"
        direction: "down"
      callbacks:
        on_left: "toggle_calendar"
        on_middle: "toggle_label"
        on_right: "next_timezone"
      animation:
        enabled: true
        duration: 500
        type: "fadeInOut"
      label_shadow:
        enabled: true
        color: "black"
        radius: 3
        offset: [1, 1]
  weather:
    type: "yasb.weather.WeatherWidget"
    options:
      label: "<span>{icon}</span> {conditions} {temp}"
      label_alt: "{location}: {conditions}, Min {min_temp}, Max {max_temp}, Humidity {humidity}"
      api_key: '53c6b436eaa649beadb50948252306'
      update_interval: 600 #Update interval in seconds, Min 600
      hide_decimal: true
      location: "Mississauga, ON"
      units: "metric"
      callbacks:
        on_left: "toggle_card"
      icons:
        sunnyDay: "\udb81\udd99"
        clearNight: "\ue3c2"
        cloudyDay: "\ue21d"
        cloudyNight: "\ue226"
        rainyDay: "\ue371"
        rainyNight: "\ue371"
        snowyIcyDay: "\udb81\udf17"
        snowyIcyNight: "\udb81\udf17"
        blizzard: "\udb81\udd99"
        default: "\udb81\udd99"
      weather_card:
        blur: True
        round_corners: True
        round_corners_type: "normal"
        border_color: "#7e8f85"
        alignment: "right"
        direction: "down"
        distance: 6
        icon_size: 48
  notes:
    type: "yasb.notes.NotesWidget"
    options:
      label: "<span>\udb82\udd0c</span> {count}"
      label_alt: "{count} notes"
      menu:
        blur: true
        round_corners: true
        round_corners_type: "normal"
        border_color: "System"
        alignment: "right"
        direction: "down"
        offset_top: 6
        offset_left: 0
        max_title_size: 150
        show_date_time: true
      icons:
        note: "\udb82\udd0c"
        delete: "\ueab8"
        copy: "\uebcc"
      callbacks:
        on_left: "toggle_menu"
        on_middle: "do_nothing"
        on_right: "toggle_label"
      label_shadow:
        enabled: true
        color: "black"
        radius: 3
        offset: [1, 1]
      animation:
        enabled: true
        duration: 600
        type: "fadeInOut"
  wallpapers:
    type: "yasb.wallpapers.WallpapersWidget"
    options:
      label: "<span>\udb83\ude09</span>"
      image_path: "C:\\Users\\nucle\\Downloads\\wALLpapers"
      change_automatically: false
      update_interval: 60
      gallery:
        enabled: true
        blur: true
        image_width: 220
        image_per_page: 8
        show_buttons: false
        orientation: "portrait"
        image_spacing: 8
        lazy_load: true
        lazy_load_delay: 80
        lazy_load_fadein: 400
        image_corner_radius: 20
        enable_cache: true
      run_after:
        - "wal -i '{image}'"
        - "pwsh -File C:\\Users\\nucle\\.config\\yasb\\inject-wal-colors.ps1"
      label_shadow:
        enabled: true
        color: "black"
        radius: 3
        offset: [ 1, 1 ]
  # cava:
  #   type: "yasb.cava.CavaWidget"
  #   options:
  #     bar_height: 12
  #     gradient: 1
  #     reverse: 0
  #     foreground: "#D3C6AA"
  #     gradient_color_1: '#bbb099'
  #     gradient_color_2: '#bbb099'
  #     bars_number: 12
  #     bar_spacing: 2
  #     bar_width: 5
  #     noise_reduction: 0
  #     framerate: 25
  #     sleep_timer: 30
  #     hide_empty: true
  #     container_padding:
  #       top: 0
  #       left: 4
  #       bottom: 0
  #       right: 4
  taskbar:
    type: "yasb.taskbar.TaskbarWidget"
    options:
      icon_size: 20
      show_only_visible: false
      strict_filtering: true
      tooltip: true
      monitor_exclusive: true
      hide_empty: true
      title_label:
        enabled: false
        show: "focused"
        min_length: 10
        max_length: 30
      ignore_apps:
        processes: []
        titles: []
        classes: []
      callbacks:
        on_left: "toggle_window"
        on_middle: "do_nothing"
        on_right: "close_app"
      animation:
        enabled: true
        type: "fadeInOut"
        duration: 200
      label_shadow:
        enabled: true
        color: "black"
        radius: 3
        offset: [1, 1]

  media:
    type: "yasb.media.MediaWidget"
    options:
      label: "<span>\udb80\udf87</span> {title}"
      label_alt: "<span>\udb80\udf87</span> {title}"
      hide_empty: false
      callbacks:
        on_left: "toggle_media_menu"
        on_middle: "do_nothing"
        on_right: "toggle_label"
      max_field_size:
        label: 60
        label_alt: 125
      show_thumbnail: true
      controls_only: false
      controls_left: true
      controls_hide: false
      thumbnail_alpha: 50
      thumbnail_padding: 0
      thumbnail_corner_radius: 8
      thumbnail_edge_fade: true
      icons:
        prev_track: "⏮"
        play: "▶"
        pause: "⏸"
        next_track: "⏭"
      media_menu:
        blur: true
        round_corners: true
        round_corners_type: "normal"
        border_color: "#7e8f85"
        alignment: "right"
        direction: "down"
        offset_top: 6
        offset_left: 0
        thumbnail_corner_radius: 8
        thumbnail_size: 160
        max_title_size: 120
        max_artist_size: 120
        show_source: true
      media_menu_icons:
        prev_track: "⏮"
        play: "▶"
        pause: "⏸"
        next_track: "⏭"
      label_shadow:
        enabled: true
        color: "black"
        radius: 1
        offset: [ 1, 1 ]
      scrolling_label:
        enabled: false
        update_interval_ms: 50
        style: "left"
        separator: " | "
        label_padding: 1
        
  # CPU, Memory, and Disk Widgets
  cpu:
    type: "yasb.cpu.CpuWidget"
    options:
      label: "<span>\uf4bc</span> {info[percent][total]}%"
      label_alt: "<span>\uf437</span> {info[histograms][cpu_percent]}"
      update_interval: 2000
      histogram_icons:
        - "\u2581"  # 0%
        - "\u2581"  # 10%
        - "\u2582"  # 20%
        - "\u2583"  # 30%
        - "\u2584"  # 40%
        - "\u2585"  # 50%
        - "\u2586"  # 60%
        - "\u2587"  # 70%
        - "\u2588"  # 80%+
      histogram_num_columns: 8
      callbacks:
        on_right: "exec cmd /c Taskmgr"
  memory:
    type: "yasb.memory.MemoryWidget"
    options:
      label: "<span>\uefc5</span> {virtual_mem_percent}%"
      label_alt: "<span>\uefc5</span> {virtual_mem_used}/{virtual_mem_total}"
      update_interval: 5000
      callbacks:
        on_left: "toggle_label"
        on_middle: "do_nothing"
        on_right: "do_nothing"
  # traffic:
  #   type: "yasb.traffic.TrafficWidget"
  #   options:
  #     label: "<span>\udb82\udcfa</span>    \uea9a{download_speed} \ueaa1{upload_speed}"
  #     label_alt: "<span>\udb82\udcfa</span> Download {download_speed} | Upload {upload_speed}"
  #     update_interval: 1000
  #     callbacks:
  #       on_left: 'toggle_label'
  #       on_right: 'exec cmd /c Taskmgr'
  systray:
    type: "yasb.systray.SystrayWidget"
    options:
      class_name: "systray"
      label_collapsed: "▼"
      label_expanded: "▶"
      label_position: "left" # Can be "left" or "right"
      icon_size: 12 # Can be any integer between 8 and 64
      pin_click_modifier: "alt" # Can be "ctrl", "alt" or "shift"
      show_unpinned: false
      show_unpinned_button: true
      show_battery: false
      show_volume: false
      show_network: false
      btn_shadow:
        enabled: true
        color: "black"
        radius: 3
        offset: [ 1, 1 ]
  bluetooth:
    type: "yasb.bluetooth.BluetoothWidget"
    options:
      label: "<span>{icon}</span> {device_count}"
      label_no_device: "No devices connected"
      label_device_separator: ", "
      max_length: 10
      max_length_ellipsis: "..."
      icons: 
        bluetooth_on: "\udb80\udcaf"
        bluetooth_off: "\udb80\udcb2"
        bluetooth_connected: "\udb80\udcb1"
      device_aliases:
        - name: "T5.0"
          alias: "\uf025"
      callbacks:
        on_left: "toggle_label"
        on_right: "exec cmd.exe /c start ms-settings:bluetooth"
      label_shadow:
        enabled: true
        color: "black"
        radius: 3
        offset: [ 1, 1 ]
  disk:
    type: "yasb.disk.DiskWidget"
    options:
        label: "<span>\uf473</span>"
        label_alt: "<span>\uf473</span>"
        group_label:
          volume_labels: ["C", "D", "E", "F", "H", "I", "J"]
          show_label_name: true 
          blur: True
          round_corners: True
          round_corners_type: "normal"
          border_color: "#7e8f85"
          alignment: "right"
          direction: "down"
          distance: 6
        callbacks:
          on_left: "toggle_group"
  power_menu:
    type: "yasb.power_menu.PowerMenuWidget"
    options:
      label: "\uf011"
      uptime: True
      blur: False
      blur_background: True
      animation_duration: 300 # Milliseconds
      button_row: 3 # Number of buttons in a row, min 1 max 5
      buttons:
        lock: ["\uf023", "Lock"]
        sleep: ["\uf186","Sleep"]
        signout: ["\uf2f5", "Sign out"]
        shutdown: ["\uf011", "Shut Down"]
        restart: ["\uf2f1", "Restart"]
        hibernate: ["\uf28e", "Hibernate"]
        cancel: ["\uf00d", "Cancel"]
      label_shadow:
        enabled: true
        color: "black"
        radius: 3
        offset: [ 1, 1 ]

  gpu:
    type: "yasb.gpu.GpuWidget"
    options:
      label: "<span>\uf4bc</span> {info[utilization]}%"
      label_alt: "<span>\uf4bc</span> {info[temp]}°C | {info[mem_used]} / {info[mem_total]}"
      update_interval: 5000
      gpu_thresholds:
        low: 25
        medium: 50
        high: 90
      histogram_icons:
        - "\u2581"  # 0%
        - "\u2581"  # 10%
        - "\u2582"  # 20%
        - "\u2583"  # 30%
        - "\u2584"  # 40%
        - "\u2585"  # 50%
        - "\u2586"  # 60%
        - "\u2587"  # 70%
        - "\u2588"  # 80%+
      histogram_num_columns: 8
      callbacks:
        on_left: "toggle_label"
      animation:
        enabled: true
        type: "fadeInOut"
        duration: 200
      container_shadow:
        enabled: true
        color: "black"
        radius: 3
        offset: [ 1, 1 ]
      label_shadow:
        enabled: true
        color: "black"
        radius: 3
        offset: [ 1, 1 ]
      progress_bar:
        enabled: true
        position: "right"
        size: 20
        thickness: 2
        color: "#57948a"
        background_color: "#23334e"
        animation: true